version: '3'
services:
    server:
        network_mode: bridge
        container_name: server
        build:
            context: .
            dockerfile: Dockerfile  
        environment:
          SECRET_KEY: "hard-secret-key"
          MONGODB_URI: "mongodb://dbserver:27017/carsclubdb"
        depends_on:
        - dbserver
        links:
        - dbserver
        ports:
        - '5000:5000'

    dbserver:
        network_mode: bridge
        container_name: dbserver
        image: 'mongo:latest'
        restart: unless-stopped
        ports:
        - '27017:27017'
        volumes:
        - ./data/db:/data/db