version: '3.2'
services:
    api1:
        container_name: api1
        build:
            context: .
            dockerfile: Dockerfile  
        environment:
          SECRET_KEY: "hard-secret-key"
          MONGODB_URI: "mongodb://dbserver:27017/carsclubdb"
        tty: true
        depends_on:
        - dbserver
        links:
        - dbserver
        ports:
        - '5001:5000'

    api2:
        container_name: api2
        build:
            context: .
            dockerfile: Dockerfile  
        environment:
            SECRET_KEY: "hard-secret-key"
            MONGODB_URI: "mongodb://dbserver:27017/carsclubdb"
        tty: true
        depends_on:
        - dbserver
        links:
        - dbserver
        ports:
        - '5002:5000'

    dbserver:
        container_name: dbserver
        image: 'mongo:latest'
        restart: unless-stopped
        tty: true
        ports:
        - '27017:27017'
        volumes:
        - ./data/db:/data/db

    loadbalancer:
        build: ./nginx
        tty: true
        links:
            - api1
            - api2
        ports:
            - '8080:8080'

    jaeger:
        image: jaegertracing/all-in-one:latest
        ports:
            - "6831:6831/udp"
            - "16686:16686"

    rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - 15672:15672
            - 5672:5672
        labels:
            NAME: "rabbitmq"